name: Worlds
description: Simple world loading plugin
author: StarTux
version: 0.1
main: com.winthier.worlds.WorldsPlugin
depend: []
commands:
  worlds:
    description: Admin interface
    permission: worlds.worlds
  wtp:
    description: World teleport
    permission: worlds.wtp
permissions:
  worlds.worlds:
    default: op
  worlds.wtp:
    default: op
