main: com.winthier.worlds.WorldsPlugin
name: Worlds

version: 0.1
api-version: 1.19

description: Simple world loading plugin
author: StarTux

depend: []
softdepend: []
loadbefore: []

commands:

  worlds:
    aliases: [ world ]
    description: Admin interface
    permission: worlds.worlds
    usage: |-
      /world list - List worlds
      /world who - List players in worlds
      /world reload - Reload config
      /world apply - (Re)apply world settings
      /world listloaded - List loaded Bukkit worlds
      /world import <world> - Import Bukkit world settings
      /world setspawn - Set world spawn
      /world load <world> [environment] - Load world
      /world unload <world> - Unload Bukkit world

  wtp:
    description: World teleport
    usage: |-
      /wtp <world> - Teleport to world.
      /wtp <player> <world> - Teleport player to world.
    permission: worlds.wtp

permissions:
  worlds.worlds:
    default: op
  worlds.wtp:
    default: op
  worlds.override:
    default: op
